
CRAWL_HAINING_TASKS = {
    'name':'haining',
    'source_url':'',
    'task_queue':'wangban:haining:an_work_urls',
    'task_check':'wangban:haining:an_url_check',
    'task_ajax':'wangban:haining:an_url_ajax',
    'html_type':'ajax',
    'tasks':[
    {'工程招标':{
    '招标公告':{
            'NONE_1':'http://www.zjhnztb.com/gczb1/zbgg1/',
            'NONE_2':'http://www.zjhnztb.com/gczb1/zbgg2/'},
    '招标答疑':{
                'NONE_1':'http://www.zjhnztb.com/gczb1/zbdy1/',
                'NONE_2':'http://www.zjhnztb.com/gczb1/zbdy2/'},
    '开标记录':{
                'NONE':'http://www.zjhnztb.com/gczb/kbjl/',},
    '中标公示':{
                'NONE_1':'http://www.zjhnztb.com/gczb1/zbgs1/',
                'NONE_2':'http://www.zjhnztb.com/gczb1/zbgs2/'},
    '结果公告':{'NONE':'http://www.zjhnztb.com/gczb/jggg/',},
    '专家公示':{'NONE':'http://www.zjhnztb.com/gczb/zjgs/',},
    '退保证金':{
            'NONE_1':'http://www.zjhnztb.com/gczb1/tbzj1/',
            'NONE_2':'http://www.zjhnztb.com/gczb1/tbzj2/',
            'NONE_3':'http://www.zjhnztb.com/gczb1/tbzj3/',},
    }},
    {'政府采购':{
    '采购公告':{
                'NONE':'http://www.zjhnztb.com/zfcg/zfzbgg/',},
    '征求意见':{'NONE':'http://www.zjhnztb.com/zfcg/zqyj/',},
    '更正公告':{'NONE':'http://www.zjhnztb.com/zfcg/gzgg/',},
    '结果公告':{'NONE':'http://www.zjhnztb.com/zfcg/zbggs/',},
    '其他公告':{'NONE':'http://www.zjhnztb.com/zfcg/qtgg/',},
    '退保证金':{'NONE':'http://www.zjhnztb.com/zfcg/zftbzj/',},
    '政采贷':{'NONE':'http://www.zjhnztb.com/zfcg/zcd/',},
    '协议供货':{'NONE':'http://www.zjhnztb.com/zfcg/xygh/',},
    }},
    {'镇街道交易':{
    '招标公告':{'NONE_1':'http://www.zjhnztb.com/zjdjy1/zjzbgg1/',
                'NONE_2':'http://www.zjhnztb.com/zjdjy1/zjzbgg2/',
                'NONE_3':'http://www.zjhnztb.com/zjdjy1/zjzbgg3/',
                'NONE_4':'http://www.zjhnztb.com/zjdjy1/zjzbgg4/',
                'NONE_5':'http://www.zjhnztb.com/zjdjy1/zjzbgg5/',
                'NONE_6':'http://www.zjhnztb.com/zjdjy1/zjzbgg6/',},
    '中标公示':{'NONE_1':'http://www.zjhnztb.com/zjdjy1/zjzbggs1/',
                'NONE_2':'http://www.zjhnztb.com/zjdjy1/zjzbggs2/',
                'NONE_3':'http://www.zjhnztb.com/zjdjy1/zjzbggs3/',
                'NONE_4':'http://www.zjhnztb.com/zjdjy1/zjzbggs4/',
                'NONE_5':'http://www.zjhnztb.com/zjdjy1/zjzbggs5/',
                'NONE_6':'http://www.zjhnztb.com/zjdjy1/zjzbggs6/',},
    '补充公告':{'NONE':'http://www.zjhnztb.com/zjdjy/bcgg/',},
    '中标公告':{'NONE':'http://www.zjhnztb.com/zjdjy/zjzbggao/',},
    }},
    {'土地交易':{
    '交易公告':{'NONE':'http://www.zjhnztb.com/ysjy/tdjy/tdjygg/',},
    '成交公告':{'NONE':'http://www.zjhnztb.com/ysjy/tdjy/tdcjgg/',},
    '退保证金':{'NONE':'http://www.zjhnztb.com/ysjy/tdjy/tdtbzj/',},
    }},
    {'产权交易':{
    '交易公告':{'NONE':'http://www.zjhnztb.com/ysjy/cqjy/cqjygg/',},
    '成交公示':{'NONE':'http://www.zjhnztb.com/ysjy/cqjy/cqcjgg/',},
    '退保证金':{'NONE':'http://www.zjhnztb.com/ysjy/cqjy/cqtbzj/',},
    }},
    {'排污权交易':{
    '交易公告':{'NONE':'http://www.zjhnztb.com/ysjy/pwqjy/pwjygg/',},
    '成交公告':{'NONE':'http://www.zjhnztb.com/ysjy/pwqjy/pwcjgg/',},
    '退保证金':{'NONE':'http://www.zjhnztb.com/ysjy/pwqjy/pwtbzj/',},
    }},
    {'用能指标交易':{
    '交易公告':{'NONE':'http://www.zjhnztb.com/ysjy/ynzb/ynjygg/',},
    '成交公告':{'NONE':'http://www.zjhnztb.com/ysjy/ynzb/yncjgg/',},
    '退保证金':{'NONE':'http://www.zjhnztb.com/ysjy/ynzb/yntbzj/',},
    }},
    {'农村产权交易':{
    '交易公告':{'市级平台':'http://www.zjhnztb.com/ysjy/nccq/ncjygg/',
                '镇街道平台':'http://www.zjhnztb.com/ysjy/zjdpt/zjjygg/'},
    '成交公告':{'市级平台':'http://www.zjhnztb.com/ysjy/nccq/nccjgg/',
                '镇街道平台':'http://www.zjhnztb.com/ysjy/zjdpt/zjcjgg/'},
    '退保证金':{'市级平台':'http://www.zjhnztb.com/ysjy/nccq/nctbzj/',},
    }},
    {'农村产权土地流转':{
    '出租(流出)信息':{'NONE':'http://www.zjhnztb.com/nccqtdlz/nccqcz/',},
    '求租(流入)信息':{'NONE':'http://www.zjhnztb.com/nccqtdlz/nccqqz/',},
    }},
    ]
}

def main():
    return CRAWL_HAINING_TASKS