

CRAWL_JIANGSHAN_TASKS = {
    'name':'jiangshan',
    'source_url':'',
    'task_queue':'wangban:jiangshan:an_work_urls',
    'task_check':'wangban:jiangshan:an_check_urls',
    'html_type':'static',
    'tasks':[
    {'工程交易':{
    '招标公告':{
        'NONE':'http://www.jsztb.org/GcjyZbgg.asp',
        '乡镇部门':'http://www.jsztb.org/JsgcZbgg.asp',
        },
    '补充（澄清）公告':{
        'NONE':'http://www.jsztb.org/GcjyBcgg.asp',
        '乡镇部门':'http://www.jsztb.org/JsgcBcgg.asp',
        },
    '开标结果公示':{
        'NONE':'http://www.jsztb.org/GcjyKbjggs.asp',
        '乡镇部门':'http://www.jsztb.org/JsgcKbjggs.asp',
        },
    '中标结果':{
        'NONE':'http://www.jsztb.org/GcjyZbjg.asp',
        '乡镇部门':'http://www.jsztb.org/JsgcZbgg.asp',
        },
    '合同订立及履行':{
        'NONE':'http://www.jsztb.org/GcjyHtdl.asp',
        '乡镇部门':'http://www.jsztb.org/JsgcHtdl.asp',
        },
    }},
    {'政府采购':{
    '采购项目公告':{
         'NONE':'http://www.jsztb.org/ZfcgCggg.asp',
         '乡镇部门':'http://www.jsztb.org/ZfcgxzCggg.asp',
         },
    '更正、中止(暂停)、澄清(答疑)':{
         'NONE':'http://www.jsztb.org/ZfcgGzcq.asp',
         '乡镇部门':'http://www.jsztb.org/ZfcgxzGzcq.asp',
         },
    '采购结果':{
         'NONE':'http://www.jsztb.org/ZfcgCgjg.asp',
         '乡镇部门':'http://www.jsztb.org/ZfcgxzCgjg.asp',
         },
    '采购合同公告':{
         'NONE':'http://www.jsztb.org/ZfcgCghtgg.asp',
         '乡镇部门':'http://www.jsztb.org/ZfcgxzCghtgg.asp',
         },
    '履约验收公告':{
         'NONE':'http://www.jsztb.org/ZfcgLynsgg.asp',
         '乡镇部门':'http://www.jsztb.org/ZfcgxzLynsgg.asp',
         },
    }},
    {'土地交易':{
    '出让公告':{'NONE':'http://www.jsztb.org/TdjyCrgg.asp',},
    '补充公告':{'NONE':'http://www.jsztb.org/TdjyBzgg.asp',},
    '成交结果公告':{'NONE':'http://www.jsztb.org/TdjyCjjggg.asp',},
    '公告公示':{'乡镇部门':'http://www.jsztb.org/nccq/rctdg.asp',}
    }},
    {'产权及其他公共资源交易':{
    '交易公告':{'NONE':'http://www.jsztb.org/QtzyJygg.asp',},
    '公告公示':{
         '集体资产':'http://www.jsztb.org/nccq/rcjtg.asp',
         '林权交易':'http://www.jsztb.org/nccq/rclqg.asp',
         '水塘养殖交易':'http://www.jsztb.org/nccq/styzg.asp',
         '其他产权交易':'http://www.jsztb.org/nccq/rcqtg.asp',
         },
    }},
    {'非政府采购':{
    '招标公告':{'乡镇部门':'http://www.jsztb.org/FzfcgZbgg.asp',},
    '成交结果及合同履约':{'乡镇部门':'http://www.jsztb.org/FzfcgCjjg.asp',},
    }},
    {'资源出让':{
    '交易公告':{'乡镇部门':'http://www.jsztb.org/ZycrJygg.asp',},
    '补充公告':{'乡镇部门':'http://www.jsztb.org/ZycrBcgg.asp',},
    '成交结果公告':{'乡镇部门':'http://www.jsztb.org/ZycrCjjggg.asp',},
    }},
    ]
}

def main():
    return CRAWL_JIANGSHAN_TASKS