from scrapy.utils.project import get_project_settings
import sys,os
SETTINGS = get_project_settings()
BASE_DIR_1 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR_2 = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR_1)
sys.path.append(BASE_DIR_2)
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'taizhou'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'wenzhou'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'ningbo'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'hangzhou'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'shaoxing'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'quzhou'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'jiaxing'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'huzhou'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'jinhua'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'lishui'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'zhejiang'))
sys.path.append(os.path.join(SETTINGS['SPIEDE_FILE_PATH'],'zhoushan'))